### ISSUE TITLE
Use 'Authorization' header field for access token

### ISSUE THREAD

**Issue by martinleopold** [StudioProcess/imagetool#10]
Can we support a

```
Authorization: Bearer <access_token>
```

header like described here: https://jwt.io/introduction/#how-do-json-web-tokens-work-

This way we have a unified way to send the token (Now it's query params for GET and JSON field in the body for POST).

Looks like it should already be supported, but it doesn't seem to work for me.

**Comment by crux23** [comment]
couldn't get it to work. apache seems to strip the authorization header. tried htaccess fixes but it didn't help. also tried to contact the hoster but they didn't reply.
so we exchange the token as json data instead.
