### ISSUE TITLE
Reload on /login (on live server) results in 404

### ISSUE THREAD

**Issue by RESL** [StudioProcess/imagetool#104]
http://ito.process.studio/login

`Not Found

The requested URL /login was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

Apache Server at ito.process.studio Port 80`

**Comment by martinleopold** [comment]
This is most likely a server issue. Apache needs to direct all requests (that don't go to `/api/*`) to the main app file (`/index.html`). Can be done in `.htaccess`
