### ISSUE TITLE
On app startup: Resume session or redirect to /login

### ISSUE THREAD

**Issue by RESL** [StudioProcess/imagetool#12]
for correct [routerLinkActive] display

**Comment by RESL** [comment]
**check if user is logged in?**
- no: -> redirect to login
- yes: -> resume session (see #32)

**Comment by martinleopold** [comment]
First introduced in 55f9f7500253d234824cb65094961ccea38fdcfc.
Finalized in b255f4494da393f12458adcf8b719675a62f45b6.
