### ISSUE TITLE
Route cleanup

### ISSUE THREAD

**Issue by martinleopold** [StudioProcess/imagetool#16]
Implement route changes as follows:

`POST /login` (Was `/user/login`)
`GET /logout` (Was `/user/logout`)

`POST /admin/register_user` (Was `/user/register`)
`POST /admin/update_user` (Was `user/update`)
`GET /admin/user_list` (See #13 + some functionality from `/user/get_userstats` before)
`GET /admin/user_stats` (Was `/user/get_userstats`. see #13)

`GET /session/reset` (See #11)
`POST /session/images` (Was `/add_images`)
`GET /session/images` (Was `/get_images`)
`POST /session/cover` (Was `/set_cover`)
`GET /session/cover` (Was `/get_cover_settings`)
`GET /session/archive` (Was `get_image_archive`)

**Comment by crux23** [comment]
done.

& additionally added
GET /get_user_details ( to get user details )
POST /session/remove ( to remove an image )
