### ISSUE TITLE
Backend: Remove sensitive config files from public repo

### ISSUE THREAD

**Issue by martinleopold** [StudioProcess/imagetool#3]
@crux23 Any sensitive config files still public? (with credentials etc)

**Comment by martinleopold** [comment]
@crux23 Isn't there a JWT secret somewhere in the config, for example?

**Comment by crux23** [comment]
jup .. config/jwt.php ... all sensitive data is in the config folder. and in the .env file in root

**Comment by crux23** [comment]
sensitive data is now only stored in the .env file.
