### ISSUE TITLE
Create warning for empty images array.

### ISSUE THREAD

**Issue by RESL** [StudioProcess/imagetool#38]
Something like:

> Es wurden noch keine Fotos hochgeladen. Wechseln Sie zu Schritt 1.

for these views:
- Titelfoto auswählen
- Titelfoto bearbeiten
- Fotos herunterladen

**Comment by martinleopold** [comment]
Resolved in 0034b685b2402a463eeb84fc806637a8ee930f04, fb7b7a60e075504e3acb6a54c89d318d2c93e026 and 8538074e3175da8159af465be6a20d2494d177c3
