### ISSUE TITLE
Backend: Secure user/register

### ISSUE THREAD

**Issue by martinleopold** [StudioProcess/imagetool#4]
@crux23 How can we secure `user/register` route, to prevent unauthorized creation of new users?

**Comment by crux23** [comment]
two ideas:
1. set a own passphrase to register, p.e. "imageToolAnmeldung". it will be always the same or has to get set manually if needed.
2. set a passphrase/token witch has auto renewal. which has to be given out by you and is limited in lifetime p.e. for one day.

**Comment by martinleopold** [comment]
Closed, followed up in #6
