### ISSUE TITLE
Customize sticker rendering

### ISSUE THREAD

**Issue by martinleopold** [StudioProcess/imagetool#55]
- [x] Font
- [x] Sticker shape from SVG
- [x] Word-wrap i.e. how text is fitted inside the sticker
- [x] Size of sticker
- [ ] Size of logos
- [x] Width of border

Note: All these just on the server, not dynamically via client request.

**Comment by RESL** [comment]
positions in final image (including gradient border)

**sticker**
size: 250px diameter
position: top right corner, margin-top: 10px, margin-right: 10px
color: gradient bottom color
text color: black

**logos** 
size: 80px height (width varies)
position: bottom left corner
- user logo: margin-left: 60px, margin-bottom: 60px
- brand logo: margin-left: 20px, margin-bottom: 60px
