### ISSUE TITLE
Test app on different browsers

### ISSUE THREAD

**Issue by RESL** [StudioProcess/imagetool#72]

**Comment by RESL** [comment]
- [x]  ~~Safari: Upload doesn't work.~~

**Comment by martinleopold** [comment]
Safari works for me: 
![screen shot 2016-10-27 at 16 22 20](https://cloud.githubusercontent.com/assets/1692826/19770970/957318e4-9c61-11e6-85a7-bb6316315736.png)
<img width="396" alt="screen shot 2016-10-27 at 16 22 17" src="https://cloud.githubusercontent.com/assets/1692826/19770979/9abfbd2a-9c61-11e6-95a1-8e274f4dbf93.png">
maybe cache problems?

**Comment by RESL** [comment]
![screen shot 2016-10-27 at 16 38 47](https://cloud.githubusercontent.com/assets/4606254/19813472/37d739c0-9d3a-11e6-8de7-27205aff428d.png)
<img width="396" alt="screen shot 2016-10-27 at 16 38 50" src="https://cloud.githubusercontent.com/assets/4606254/19813473/37e9f1f0-9d3a-11e6-9674-f4d6fc713a15.png">

possibly only on older versions?

**Comment by martinleopold** [comment]
Tested:
- Chrome 54
- Firefox 48, 49
- Safari 9, 10
- IE 10, 11 (=Edge)
