### ISSUE TITLE
Uploading an image results in 401 error (Unauthorized)

### ISSUE THREAD

**Issue by RESL** [StudioProcess/imagetool#94]
`POST http://ito.process.studio/api/session/images 401 (Unauthorized)`

`upload error Response 
{_body: "{"status":"error","message":"Authentication failed…"The token could not be parsed from the request"}", status: 401, ok: false, statusText: "Unauthorized", headers: Headers…}_body: "{"status":"error","message":"Authentication failed; Something is wrong. Maybe no token provided.","exception":"The token could not be parsed from the request"}"headers: Headersok: falsestatus: 401statusText: "Unauthorized"type: 2url: "http://ito.process.studio/api/session/images"__proto__: Body`

**Comment by martinleopold** [comment]
Fixed.
